const data=[
    {
        id: 0,
         SNo: "1",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"75%",
         Actions:"...",
    },
    {
        id: 0,
         SNo: "2",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"75%",
         Actions:"...",
    },
    {
        id: 0,
         SNo: "3",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"75%",
         Actions:"...",
    },
    {
        id: 0,
         SNo: "4",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"75%",
         Actions:"...",
    },
    {
        id: 0,
         SNo: "5",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"45%",
         Actions:"...",
    },
    {
        id: 0,
         SNo: "6",
         StudentName:"Mahima Singh",
         StudentID:"01234",
         Course:"B.Tech",
         Class:"CSE-1",
         TotalAttendance:"45%",
         Actions:"...",
    },
      
]

export default data;